name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.1'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Web and API Tests
        run: |
          pytest tests/web --maxfail=1 --disable-warnings -q
          pytest tests/api --maxfail=1 --disable-warnings -q
      - name: Run Mobile Tests
        run: |
          pytest tests/mobile --maxfail=1 --disable-warnings -q
